enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Swipe controls' 'Disable auto captions' 'Custom branding' 'Change header' 'Hide video action buttons' 'Navigation buttons' 'Hide player overlay buttons' 'Change form factor' 'Disable rolling number animations' 'Hide Shorts components' 'Hide timestamp' 'Custom player overlay opacity' 'Wide search bar' 'Open Shorts in regular player' 'Change start page' 'Theme' 'Alternative thumbnails' 'Enable debugging' 'Spoof device dimensions'"


