enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Swipe controls' 'Hide player overlay buttons' 'Hide Shorts components' 'Hide timestamp' 'Custom player overlay opacity' 'Wide search bar' 'Shorts autoplay' 'Open Shorts in regular player' 'Change start page' 'Disable resuming Shorts on startup' 'Theme' 'Spoof device dimensions' 'GmsCore support'"

